// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: grpc/proto.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RAServer_RequestCS_FullMethodName = "/RAServer/RequestCS"
	RAServer_ReplyCS_FullMethodName   = "/RAServer/ReplyCS"
)

// RAServerClient is the client API for RAServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RAServerClient interface {
	RequestCS(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
	ReplyCS(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Empty, error)
}

type rAServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRAServerClient(cc grpc.ClientConnInterface) RAServerClient {
	return &rAServerClient{cc}
}

func (c *rAServerClient) RequestCS(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RAServer_RequestCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAServerClient) ReplyCS(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RAServer_ReplyCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAServerServer is the server API for RAServer service.
// All implementations must embed UnimplementedRAServerServer
// for forward compatibility.
type RAServerServer interface {
	RequestCS(context.Context, *Request) (*Empty, error)
	ReplyCS(context.Context, *Reply) (*Empty, error)
	mustEmbedUnimplementedRAServerServer()
}

// UnimplementedRAServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAServerServer struct{}

func (UnimplementedRAServerServer) RequestCS(context.Context, *Request) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCS not implemented")
}
func (UnimplementedRAServerServer) ReplyCS(context.Context, *Reply) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyCS not implemented")
}
func (UnimplementedRAServerServer) mustEmbedUnimplementedRAServerServer() {}
func (UnimplementedRAServerServer) testEmbeddedByValue()                  {}

// UnsafeRAServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAServerServer will
// result in compilation errors.
type UnsafeRAServerServer interface {
	mustEmbedUnimplementedRAServerServer()
}

func RegisterRAServerServer(s grpc.ServiceRegistrar, srv RAServerServer) {
	// If the following call pancis, it indicates UnimplementedRAServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RAServer_ServiceDesc, srv)
}

func _RAServer_RequestCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServerServer).RequestCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAServer_RequestCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServerServer).RequestCS(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAServer_ReplyCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServerServer).ReplyCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAServer_ReplyCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServerServer).ReplyCS(ctx, req.(*Reply))
	}
	return interceptor(ctx, in, info, handler)
}

// RAServer_ServiceDesc is the grpc.ServiceDesc for RAServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RAServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RAServer",
	HandlerType: (*RAServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCS",
			Handler:    _RAServer_RequestCS_Handler,
		},
		{
			MethodName: "ReplyCS",
			Handler:    _RAServer_ReplyCS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
